version: "3.9"

services:
  db:
    image: postgres:15
    container_name: audio-db
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: audio
    ports:
      - "7432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: audio-backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: demo
      DB_PASSWORD: demo
      DB_NAME: audio
      PORT: 5000
    ports:
      - "5050:5000"
    depends_on:
      - db

volumes:
  pgdata:
